import os
from pathlib import Path

from dotenv import load_dotenv


BACKEND_DIRECTORY = Path(__file__).resolve().parent
ENV_FILE = BACKEND_DIRECTORY / ".env"

load_dotenv(ENV_FILE)


FRONTEND_URL = os.getenv(
    "FRONTEND_URL",
    "http://127.0.0.1:5173",
)
#Weather
WEATHER_API_KEY = os.getenv("WEATHER_API_KEY")
#HA
HOME_ASSISTANT_URL = os.getenv("HOME_ASSISTANT_URL", "").rstrip("/")
HOME_ASSISTANT_TOKEN = os.getenv("HOME_ASSISTANT_TOKEN", "")
#Spotify
SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET")
SPOTIFY_REDIRECT_URI = os.getenv(
    "SPOTIFY_REDIRECT_URI",
    "http://127.0.0.1:8000/api/spotify/callback",
)
#Github
GITHUB_USERNAME = os.getenv("GITHUB_USERNAME")
#Bambu-Entities
BAMBU_ONLINE_ENTITY = os.getenv("BAMBU_ONLINE_ENTITY")
BAMBU_PRINT_STATUS_ENTITY = os.getenv("BAMBU_PRINT_STATUS_ENTITY")
BAMBU_NOZZLE_TEMPERATURE_ENTITY = os.getenv("BAMBU_NOZZLE_TEMPERATURE_ENTITY")
BAMBU_PRINT_PROGRESS_ENTITY = os.getenv("BAMBU_PRINT_PROGRESS_ENTITY")
BAMBU_BED_TEMPERATURE_ENTITY = os.getenv(
    "BAMBU_BED_TEMPERATURE_ENTITY"
)
BAMBU_BED_TARGET_TEMPERATURE_ENTITY = os.getenv(
    "BAMBU_BED_TARGET_TEMPERATURE_ENTITY"
)
BAMBU_NOZZLE_TARGET_TEMPERATURE_ENTITY = os.getenv(
    "BAMBU_NOZZLE_TARGET_TEMPERATURE_ENTITY"
)

BAMBU_CURRENT_LAYER_ENTITY = os.getenv(
    "BAMBU_CURRENT_LAYER_ENTITY"
)
BAMBU_TOTAL_LAYER_COUNT_ENTITY = os.getenv(
    "BAMBU_TOTAL_LAYER_COUNT_ENTITY"
)
BAMBU_REMAINING_TIME_ENTITY = os.getenv(
    "BAMBU_REMAINING_TIME_ENTITY"
)
BAMBU_TASK_NAME_ENTITY = os.getenv(
    "BAMBU_TASK_NAME_ENTITY"
)

BAMBU_PRINT_BED_TYPE_ENTITY = os.getenv(
    "BAMBU_PRINT_BED_TYPE_ENTITY"
)
BAMBU_NOZZLE_SIZE_ENTITY = os.getenv(
    "BAMBU_NOZZLE_SIZE_ENTITY"
)
BAMBU_NOZZLE_TYPE_ENTITY = os.getenv(
    "BAMBU_NOZZLE_TYPE_ENTITY"
)

BAMBU_COVER_IMAGE_ENTITY = os.getenv(
    "BAMBU_COVER_IMAGE_ENTITY"
)
BAMBU_CAMERA_ENTITY = os.getenv(
    "BAMBU_CAMERA_ENTITY"
)
BAMBU_PRINTER_NAME_ENTITY = os.getenv(
    "BAMBU_PRINTER_NAME_ENTITY"
)
BAMBU_WIFI_SIGNAL_ENTITY = os.getenv(
    "BAMBU_WIFI_SIGNAL_ENTITY"
)

BAMBU_PRINT_TYPE_ENTITY = os.getenv(
    "BAMBU_PRINT_TYPE_ENTITY"
)
BAMBU_EXTRUDER_FILAMENT_ENTITY = os.getenv(
    "BAMBU_EXTRUDER_FILAMENT_ENTITY"
)
BAMBU_PRINT_LENGTH_ENTITY = os.getenv(
    "BAMBU_PRINT_LENGTH_ENTITY"
)
BAMBU_PRINT_WEIGHT_ENTITY = os.getenv(
    "BAMBU_PRINT_WEIGHT_ENTITY"
)
BAMBU_PRINTABLE_OBJECTS_ENTITY = os.getenv(
    "BAMBU_PRINTABLE_OBJECTS_ENTITY"
)
BAMBU_TOTAL_USAGE_ENTITY = os.getenv(
    "BAMBU_TOTAL_USAGE_ENTITY"
)

BAMBU_CURRENT_STAGE_ENTITY = os.getenv(
    "BAMBU_CURRENT_STAGE_ENTITY"
)

BAMBU_END_TIME_ENTITY = os.getenv(
    "BAMBU_END_TIME_ENTITY"
)
BAMBU_START_TIME_ENTITY = os.getenv(
    "BAMBU_START_TIME_ENTITY"
)

BAMBU_CAMERA_SWITCH_ENTITY = os.getenv(
    "BAMBU_CAMERA_SWITCH_ENTITY"
)
BAMBU_IMAGE_SENSOR_CAMERA_SWITCH_ENTITY = os.getenv(
    "BAMBU_IMAGE_SENSOR_CAMERA_SWITCH_ENTITY"
)

BAMBU_AMS_ONLINE_ENTITY = os.getenv(
    "BAMBU_AMS_ONLINE_ENTITY"
)
BAMBU_AMS_HUMIDITY_ENTITY = os.getenv(
    "BAMBU_AMS_HUMIDITY_ENTITY"
)
BAMBU_AMS_HUMIDITY_INDEX_ENTITY = os.getenv(
    "BAMBU_AMS_HUMIDITY_INDEX_ENTITY"
)
BAMBU_AMS_TEMPERATURE_ENTITY = os.getenv(
    "BAMBU_AMS_TEMPERATURE_ENTITY"
)
BAMBU_AMS_TRAY1_ENTITY = os.getenv(
    "BAMBU_AMS_TRAY1_ENTITY"
)
BAMBU_AMS_TRAY2_ENTITY = os.getenv(
    "BAMBU_AMS_TRAY2_ENTITY"
)
BAMBU_AMS_TRAY3_ENTITY = os.getenv(
    "BAMBU_AMS_TRAY3_ENTITY"
)
BAMBU_AMS_TRAY4_ENTITY = os.getenv(
    "BAMBU_AMS_TRAY4_ENTITY"
)
BAMBU_AMS_ACTIVE_TRAY_ENTITY = os.getenv(
    "BAMBU_AMS_ACTIVE_TRAY_ENTITY"
)

BAMBU_EXTERNAL_SPOOL_ACTIVE_ENTITY = os.getenv(
    "BAMBU_EXTERNAL_SPOOL_ACTIVE_ENTITY"
)
BAMBU_EXTERNAL_SPOOL_FILAMENT_ENTITY = os.getenv(
    "BAMBU_EXTERNAL_SPOOL_FILAMENT_ENTITY"
)

BAMBU_ERROR_ENTITY = os.getenv(
    "BAMBU_ERROR_ENTITY"
)

BAMBU_CHAMBER_FAN_ENTITY = os.getenv(
    "BAMBU_CHAMBER_FAN_ENTITY"
)
BAMBU_AUX_FAN_ENTITY = os.getenv(
    "BAMBU_AUX_FAN_ENTITY"
)
BAMBU_COOLING_FAN_ENTITY = os.getenv(
    "BAMBU_COOLING_FAN_ENTITY"
)
BAMBU_CHAMBER_FAN_SPEED_ENTITY = os.getenv(
    "BAMBU_CHAMBER_FAN_SPEED_ENTITY"
)
BAMBU_AUX_FAN_SPEED_ENTITY = os.getenv(
    "BAMBU_AUX_FAN_SPEED_ENTITY"
)
BAMBU_COOLING_FAN_SPEED_ENTITY = os.getenv(
    "BAMBU_COOLING_FAN_SPEED_ENTITY"
)

BAMBU_CHAMBER_LIGHT_ENTITY = os.getenv(
    "BAMBU_CHAMBER_LIGHT_ENTITY"
)

BAMBU_PRINTING_SPEED_ENTITY = os.getenv(
    "BAMBU_PRINTING_SPEED_ENTITY"
)
BAMBU_FORCE_REFRESH_ENTITY = os.getenv(
    "BAMBU_FORCE_REFRESH_ENTITY"
)
BAMBU_PAUSE_ENTITY = os.getenv(
    "BAMBU_PAUSE_ENTITY"
)
BAMBU_RESUME_ENTITY = os.getenv(
    "BAMBU_RESUME_ENTITY"
)
BAMBU_STOP_ENTITY = os.getenv(
    "BAMBU_STOP_ENTITY"
)

BAMBU_GCODE_FILE_DOWNLOAD_ENTITY = os.getenv(
    "BAMBU_GCODE_FILE_DOWNLOAD_ENTITY"
)
BAMBU_GCODE_FILE_NAME_ENTITY = os.getenv(
    "BAMBU_GCODE_FILE_NAME_ENTITY"
)
BAMBU_MODEL_ENTITY = os.getenv(
    "BAMBU_MODEL_ENTITY"
)